<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Publisher;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // Get all publishers indexed by name for quick lookup
        $publishers = Publisher::all()->keyBy('name');

        $books = [
            // ===== FICTION =====
            [
                'title' => 'The Great Gatsby',
                'description' => 'A classic American novel set in the Jazz Age, exploring themes of decadence, idealism, and the American Dream through the eyes of narrator Nick Carraway.',
                'price' => 224775,
                'isbn' => '978-0743273565',
                'pages' => 180,
                'language' => 'English',
                'publication_year' => 1925,
                'publisher_id' => $publishers['Charles Scribner\'s Sons']->id ?? null,
                'status' => 'available',
                'author_id' => 4,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/the-great-gatsby-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Classic', 'Literary Fiction', 'Drama']),
                'weight_grams' => 220,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],
            [
                'title' => 'Pride and Prejudice',
                'description' => 'Elizabeth Bennet navigates matters of morality, education, and marriage in the society of the landed gentry of early 19th-century England.',
                'price' => 269730,
                'isbn' => '978-0141439518',
                'pages' => 432,
                'language' => 'English',
                'publication_year' => 1813,
                'publisher_id' => $publishers['Penguin Classics']->id ?? null,
                'status' => 'available',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/pride-and-prejudice-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Romance', 'Literary Fiction', 'Classic']),
                'weight_grams' => 390,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],
            [
                'title' => 'Kafka on the Shore',
                'description' => 'A teenage boy runs away from home to escape an Oedipal prophecy. In another narrative, a man who wakes up to find that his name, and the memory of his body, have been wiped from the world.',
                'price' => 329790,
                'isbn' => '978-1400079278',
                'pages' => 505,
                'language' => 'English',
                'publication_year' => 2002,
                'publisher_id' => $publishers['Knopf']->id ?? null,
                'status' => 'available',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/kafka-on-the-shore-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Magical Realism', 'Surrealism', 'Literary Fiction']),
                'weight_grams' => 420,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],
            [
                'title' => 'The Midnight Library',
                'description' => 'Nora Seed finds herself in a library between life and death where she can explore the different lives she could have lived and make different choices.',
                'price' => 299850,
                'isbn' => '978-0020468623',
                'pages' => 304,
                'language' => 'English',
                'publication_year' => 2020,
                'publisher_id' => $publishers['Viking']->id ?? null,
                'status' => 'available',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/The Midnight Library.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fiction', 'Fantasy', 'Contemporary']),
                'weight_grams' => 350,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],

            // ===== NON-FICTION =====
            [
                'title' => 'The Psychology of Money',
                'description' => 'Timeless lessons on wealth, greed, and happiness through a collection of essays on how people think about money and make financial decisions.',
                'price' => 269730,
                'isbn' => '978-0857197689',
                'pages' => 256,
                'language' => 'English',
                'publication_year' => 2020,
                'publisher_id' => $publishers['Harriman House']->id ?? null,
                'status' => 'available',
                'author_id' => 14,
                'category_id' => 2,
                'cover_image_url' => 'product_image/front/the-psychology-of-money-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Finance', 'Psychology', 'Business']),
                'weight_grams' => 290,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],

            // ===== SCIENCE FICTION =====
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'description' => 'The first book in the Harry Potter series. Follow young Harry as he discovers his magical heritage and attends Hogwarts School of Witchcraft and Wizardry.',
                'price' => 374850,
                'isbn' => '978-0747532699',
                'pages' => 223,
                'language' => 'English',
                'publication_year' => 1997,
                'publisher_id' => $publishers['Bloomsbury Publishing']->id ?? null,
                'status' => 'available',
                'author_id' => 1,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/harry-potter-and-the-philosopher-s-stone-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fantasy', 'Magic', 'Adventure']),
                'weight_grams' => 350,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],
            [
                'title' => 'Dune',
                'description' => 'An epic science fiction novel about Paul Atreides, a young man destined to lead humanity to a brighter future on the desert planet Arrakis.',
                'price' => 389820,
                'isbn' => '978-0441172719',
                'pages' => 688,
                'language' => 'English',
                'publication_year' => 1965,
                'publisher_id' => $publishers['Ace Books']->id ?? null,
                'status' => 'available',
                'author_id' => 7,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/dune-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Science Fiction', 'Epic', 'Adventure']),
                'weight_grams' => 640,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],
            [
                'title' => 'Foundation',
                'description' => 'The story of humanity\'s last attempt to preserve civilization, as a great empire crumbles. Hari Seldon foresees the fall and creates a refuge of knowledge.',
                'price' => 314685,
                'isbn' => '978-0553293357',
                'pages' => 247,
                'language' => 'English',
                'publication_year' => 1951,
                'publisher_id' => $publishers['Bantam Spectra']->id ?? null,
                'status' => 'available',
                'author_id' => 8,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/foundation-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Science Fiction', 'Epic', 'Classic']),
                'weight_grams' => 350,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],
            [
                'title' => 'The Handmaid\'s Tale',
                'description' => 'In a dystopian future, a woman is forced to bear children for the state in this chilling exploration of power, freedom, and survival.',
                'price' => 329790,
                'isbn' => '978-0385490238',
                'pages' => 395,
                'language' => 'English',
                'publication_year' => 1985,
                'publisher_id' => $publishers['Houghton Mifflin']->id ?? null,
                'status' => 'available',
                'author_id' => 11,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/The Handmaid Tale.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Dystopian', 'Science Fiction', 'Political']),
                'weight_grams' => 390,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],

            // ===== MYSTERY & THRILLER =====
            [
                'title' => 'The Shining',
                'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
                'price' => 299850,
                'isbn' => '978-0307743657',
                'pages' => 447,
                'language' => 'English',
                'publication_year' => 1977,
                'publisher_id' => $publishers['Doubleday']->id ?? null,
                'status' => 'available',
                'author_id' => 2,
                'category_id' => 4,
                'cover_image_url' => 'product_image/front/the-shining-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Horror', 'Psychological', 'Supernatural']),
                'weight_grams' => 420,
                'is_featured' => 1,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],
            [
                'title' => 'Murder on the Orient Express',
                'description' => 'Hercule Poirot investigates a murder aboard the luxurious Orient Express train when a wealthy American passenger is found dead in his compartment.',
                'price' => 254485,
                'isbn' => '978-0062693662',
                'pages' => 256,
                'language' => 'English',
                'publication_year' => 1934,
                'publisher_id' => $publishers['Collins Crime Club']->id ?? null,
                'status' => 'available',
                'author_id' => 3,
                'category_id' => 4,
                'cover_image_url' => 'product_image/front/Murder on the Orient Express.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Mystery', 'Crime', 'Detective']),
                'weight_grams' => 280,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],

            // ===== ROMANCE =====
            [
                'title' => 'A Game of Thrones',
                'description' => 'The first book in the epic A Song of Ice and Fire series. Political intrigue, war, and dragons in the Seven Kingdoms of Westeros.',
                'price' => 449780,
                'isbn' => '978-0553103540',
                'pages' => 694,
                'language' => 'English',
                'publication_year' => 1996,
                'publisher_id' => $publishers['Bantam Books']->id ?? null,
                'status' => 'available',
                'author_id' => 4,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/a-game-of-thrones-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fantasy', 'Epic', 'Dark Fantasy']),
                'weight_grams' => 650,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],

            // ===== BIOGRAPHY =====
            [
                'title' => 'Educated',
                'description' => 'A memoir about a young woman who leaves her survivalist family and becomes educated, going from the mountains of Idaho to Cambridge University.',
                'price' => 359235,
                'isbn' => '978-0399590504',
                'pages' => 352,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Random House']->id ?? null,
                'status' => 'available',
                'author_id' => 9,
                'category_id' => 6,
                'cover_image_url' => 'product_image/front/Educated.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Memoir', 'Biography', 'Education']),
                'weight_grams' => 420,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],
            [
                'title' => 'Becoming',
                'description' => 'Michelle Obama invites readers into her world, chronicling her life from childhood through her years as First Lady of the United States.',
                'price' => 374850,
                'isbn' => '978-1524763138',
                'pages' => 426,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Crown Publishing Group']->id ?? null,
                'status' => 'available',
                'author_id' => 10,
                'category_id' => 6,
                'cover_image_url' => 'product_image/front/becoming-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Memoir', 'Biography', 'Politics']),
                'weight_grams' => 480,
                'is_featured' => 1,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],

            // ===== HISTORY =====
            [
                'title' => 'Sapiens History Edition',
                'description' => 'A comprehensive history of humankind from the Stone Age to the modern world, exploring how Sapiens came to dominate the globe.',
                'price' => 359820,
                'isbn' => '978-0062316103',
                'pages' => 500,
                'language' => 'Spanish',
                'publication_year' => 2014,
                'publisher_id' => $publishers['Debate']->id ?? null,
                'status' => 'available',
                'author_id' => 12,
                'category_id' => 7,
                'cover_image_url' => 'product_image/front/sapiens-a-brief-history-of-humankind-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['History', 'Science', 'Society']),
                'weight_grams' => 520,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],

            // ===== SELF-HELP =====
            [
                'title' => 'Atomic Habits',
                'description' => 'A comprehensive guide to breaking bad habits and adopting good ones through small, incremental changes that lead to remarkable results.',
                'price' => 284535,
                'isbn' => '978-0735211292',
                'pages' => 320,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Avery']->id ?? null,
                'status' => 'available',
                'author_id' => 13,
                'category_id' => 8,
                'cover_image_url' => 'product_image/front/atomic-habits-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Self-Help', 'Psychology', 'Productivity']),
                'weight_grams' => 380,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 15,
            ],

            // ===== ADDITIONAL BOOKS WITH DIFFERENT LANGUAGES =====
            [
                'title' => 'The Lord of the Rings',
                'description' => 'An epic fantasy novel following Frodo Baggins on a perilous quest to destroy the One Ring and save Middle-earth from darkness.',
                'price' => 439950,
                'isbn' => '978-0544003415',
                'pages' => 1216,
                'language' => 'English',
                'publication_year' => 1954,
                'publisher_id' => $publishers['Allen & Unwin']->id ?? null,
                'status' => 'available',
                'author_id' => 17,
                'category_id' => 9,
                'cover_image_url' => 'product_image/front/The Lord of the Rings.jpg',
                'images' => json_encode([]),
                'weight_grams' => 800,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 15,
            ],
            [
                'title' => 'Der Blechtrommel',
                'description' => 'Ein Meisterwerk der deutschen Literatur. Die Geschichte eines Jungen, der mit drei Jahren aufhört zu wachsen und die Ereignisse rund um das Naziregime beobachtet.',
                'price' => 429810,
                'isbn' => '978-3570193914',
                'pages' => 464,
                'language' => 'German',
                'publication_year' => 1959,
                'publisher_id' => $publishers['Klett-Cotta']->id ?? null,
                'status' => 'available',
                'author_id' => 19,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/Der Blechtrommel.jpg',
                'images' => json_encode([]),
                'weight_grams' => 560,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 10,
            ],
            [
                'title' => 'Il Nome della Rosa',
                'description' => 'Un capolavoro della letteratura italiana. Un giallo mistico ambientato in un monastero medievale con il famoso detective Guglielmo di Baskerville.',
                'price' => 419950,
                'isbn' => '978-8817114394',
                'pages' => 635,
                'language' => 'Italian',
                'publication_year' => 1980,
                'publisher_id' => $publishers['Bompiani']->id ?? null,
                'status' => 'available',
                'author_id' => 18,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/Il Nome della Rosa.jpg',
                'images' => json_encode([]),
                'weight_grams' => 570,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 10,
            ],
            [
                'title' => '三体',
                'description' => '一部宏大的科幻小说,讲述人类与外星文明之间的冲突和交互。',
                'price' => 299730,
                'isbn' => '978-7536692930',
                'pages' => 400,
                'language' => 'Chinese',
                'publication_year' => 2008,
                'publisher_id' => $publishers['重庆出版社']->id ?? null,
                'status' => 'available',
                'author_id' => 3,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/三体.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Science Fiction', 'Epic', 'Hard SF']),
                'weight_grams' => 480,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 10,
            ],
            [
                'title' => 'ノルウェイの森',
                'description' => 'ノルウェイの森は、村上春樹の長編小説で、青年の内面世界と愛、喪失、孤独を描いている。',
                'price' => 259840,
                'isbn' => '978-4101102017',
                'pages' => 426,
                'language' => 'Japanese',
                'publication_year' => 1987,
                'publisher_id' => $publishers['新潮社']->id ?? null,
                'status' => 'available',
                'author_id' => 6,
                'category_id' => 5,
                'cover_image_url' => 'product_image/front/ノルウェイの森.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Contemporary', 'Romance', 'Literary']),
                'weight_grams' => 430,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 10,
            ],
            [
                'title' => '82년생 김지영',
                'description' => '현대 한국 여성의 삶과 사회적 압박을 다루는 감정적이고 강력한 페미니스트 소설.',
                'price' => 159730,
                'isbn' => '978-1162247380',
                'pages' => 252,
                'language' => 'Korean',
                'publication_year' => 2020,
                'publisher_id' => $publishers['민음사']->id ?? null,
                'status' => 'available',
                'author_id' => 7,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/82년생 김지영.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Contemporary', 'Feminist', 'Drama']),
                'weight_grams' => 290,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'Cem Anos de Solidão',
                'description' => 'Uma obra-prima da literatura latino-americana que narra a história de sete gerações da família Buendía.',
                'price' => 329850,
                'isbn' => '978-9500726589',
                'pages' => 472,
                'language' => 'Portuguese',
                'publication_year' => 1999,
                'publisher_id' => $publishers['Editorial Sudamericana']->id ?? null,
                'status' => 'available',
                'author_id' => 8,
                'category_id' => 1,
                'cover_image_url' => 'product_image/front/Cem-Anos-de-Solidão.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Literary', 'Magical Realism', 'Latin American']),
                'weight_grams' => 520,
                'is_featured' => 1,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['isbn' => $book['isbn']],
                $book
            );
        }
    }
}

