<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Publisher;

class PublisherSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $publishers = [
            [
                'name' => 'Bloomsbury Publishing',
                'description' => 'Leading independent British publisher of books for adults and children.',
                'website' => 'https://www.bloomsbury.com',
                'email' => 'info@bloomsbury.com',
                'phone' => '+44-203-0077299',
                'country' => 'United Kingdom',
                'city' => 'London',
                'is_active' => true,
            ],
            [
                'name' => 'Doubleday',
                'description' => 'Major American book publisher, known for fiction and non-fiction works.',
                'website' => 'https://www.doubleday.com',
                'email' => 'info@doubleday.com',
                'phone' => '+1-212-5720000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Charles Scribner\'s Sons',
                'description' => 'Prestigious American publisher with a long tradition of quality literature.',
                'website' => 'https://www.scribner.com',
                'email' => 'info@scribner.com',
                'phone' => '+1-212-6886000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Penguin Classics',
                'description' => 'Publisher of classic literature and scholarly works.',
                'website' => 'https://www.penguin.com',
                'email' => 'info@penguin.com',
                'phone' => '+44-2073100000',
                'country' => 'United Kingdom',
                'city' => 'London',
                'is_active' => true,
            ],
            [
                'name' => 'Collins Crime Club',
                'description' => 'Publisher specializing in mystery and crime novels.',
                'website' => 'https://www.collins.co.uk',
                'email' => 'info@collins.co.uk',
                'phone' => '+44-2073100000',
                'country' => 'United Kingdom',
                'city' => 'London',
                'is_active' => true,
            ],
            [
                'name' => 'Knopf',
                'description' => 'Prestigious American publisher of literary fiction and general nonfiction.',
                'website' => 'https://www.knopfdoubleday.com',
                'email' => 'info@knopf.com',
                'phone' => '+1-212-5720000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Ace Books',
                'description' => 'Publisher specializing in science fiction and fantasy.',
                'website' => 'https://www.penguin.com/publishers/ace-books',
                'email' => 'info@acebooks.com',
                'phone' => '+1-212-3662000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Bantam Spectra',
                'description' => 'Publisher of science fiction, fantasy, and speculative fiction.',
                'website' => 'https://www.bantam.com',
                'email' => 'info@bantam.com',
                'phone' => '+1-212-5720000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Random House',
                'description' => 'One of the world\'s largest general trade book publishers.',
                'website' => 'https://www.randomhouse.com',
                'email' => 'info@randomhouse.com',
                'phone' => '+1-212-7510000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Crown Publishing Group',
                'description' => 'Publisher of commercial non-fiction, including memoirs and biography.',
                'website' => 'https://www.penguinrandomhouse.com',
                'email' => 'info@crown.com',
                'phone' => '+1-212-7510000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Houghton Mifflin',
                'description' => 'American publisher of novels, non-fiction, and educational materials.',
                'website' => 'https://www.houghtonmifflinbooks.com',
                'email' => 'info@hmhco.com',
                'phone' => '+1-617-3516000',
                'country' => 'United States',
                'city' => 'Boston',
                'is_active' => true,
            ],
            [
                'name' => 'Bantam Books',
                'description' => 'Major American publisher of mass market paperback and hardcover books.',
                'website' => 'https://www.bantam.com',
                'email' => 'info@bantam.com',
                'phone' => '+1-212-5720000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Harper',
                'description' => 'American publisher of books across many genres.',
                'website' => 'https://www.harpercollins.com',
                'email' => 'info@harper.com',
                'phone' => '+1-212-2075000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Avery',
                'description' => 'Publisher of health, wellness, and personal development books.',
                'website' => 'https://www.penguinrandomhouse.com',
                'email' => 'info@avery.com',
                'phone' => '+1-212-3662000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Harriman House',
                'description' => 'British publisher specializing in business and finance books.',
                'website' => 'https://www.harriman-house.com',
                'email' => 'info@harriman-house.com',
                'phone' => '+44-1730-233870',
                'country' => 'United Kingdom',
                'city' => 'London',
                'is_active' => true,
            ],
            [
                'name' => 'Viking',
                'description' => 'American publisher of literary fiction and non-fiction.',
                'website' => 'https://www.penguin.com/publishers/viking',
                'email' => 'info@viking.com',
                'phone' => '+1-212-3662000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Scribner',
                'description' => 'American publisher known for quality fiction and memoirs.',
                'website' => 'https://www.scribner.com',
                'email' => 'info@scribner.com',
                'phone' => '+1-212-6886000',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Chilton Books',
                'description' => 'Publisher specializing in technical and automotive books.',
                'website' => 'https://www.chiltonbooks.com',
                'email' => 'info@chiltonbooks.com',
                'phone' => '+1-610-9021888',
                'country' => 'United States',
                'city' => 'Philadelphia',
                'is_active' => true,
            ],
            [
                'name' => 'Gnome Press',
                'description' => 'Historic science fiction publisher.',
                'website' => 'https://www.gnomepress.com',
                'email' => 'info@gnomepress.com',
                'phone' => '+1-718-4761234',
                'country' => 'United States',
                'city' => 'New York',
                'is_active' => true,
            ],
            [
                'name' => 'Gramedia Pustaka Utama',
                'description' => 'Leading Indonesian book publisher with diverse catalog.',
                'website' => 'https://www.gramedia.com',
                'email' => 'info@gramedia.com',
                'phone' => '+62-21-5350000',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'is_active' => true,
            ],
            [
                'name' => 'Mizan Publishing',
                'description' => 'Indonesian publisher specializing in Islamic literature and general books.',
                'website' => 'https://www.mizan.co.id',
                'email' => 'info@mizan.co.id',
                'phone' => '+62-21-7274570',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'is_active' => true,
            ],
            [
                'name' => 'Elex Media Komputindo',
                'description' => 'Indonesian publisher known for technology and business books.',
                'website' => 'https://www.elexmedia.id',
                'email' => 'info@elexmedia.id',
                'phone' => '+62-21-5350000',
                'country' => 'Indonesia',
                'city' => 'Jakarta',
                'is_active' => true,
            ],
            [
                'name' => 'Allen & Unwin',
                'description' => 'British publisher renowned for fiction, children\'s books, and mythology.',
                'website' => 'https://www.allenandunwin.co.uk',
                'email' => 'info@allenandunwin.co.uk',
                'phone' => '+44-1264-810000',
                'country' => 'United Kingdom',
                'city' => 'London',
                'is_active' => true,
            ],
            [
                'name' => 'Bompiani',
                'description' => 'Italian publisher of literary works and international literature.',
                'website' => 'https://www.bompiani.it',
                'email' => 'info@bompiani.it',
                'phone' => '+39-02-40409000',
                'country' => 'Italy',
                'city' => 'Milan',
                'is_active' => true,
            ],
            [
                'name' => 'Klett-Cotta',
                'description' => 'German publisher specializing in literature, philosophy, and history.',
                'website' => 'https://www.klett-cotta.de',
                'email' => 'info@klett-cotta.de',
                'phone' => '+49-711-6672000',
                'country' => 'Germany',
                'city' => 'Stuttgart',
                'is_active' => true,
            ],
            [
                'name' => 'Debate',
                'description' => 'Spanish publisher of literature and essays.',
                'website' => 'https://www.debolsillo.com',
                'email' => 'info@debolsillo.com',
                'phone' => '+34-93-4066000',
                'country' => 'Spain',
                'city' => 'Barcelona',
                'is_active' => true,
            ],
            [
                'name' => 'Le Livre de Poche',
                'description' => 'French publisher of pocket books and literature.',
                'website' => 'https://www.livredepoche.com',
                'email' => 'info@livredepoche.com',
                'phone' => '+33-1-42160000',
                'country' => 'France',
                'city' => 'Paris',
                'is_active' => true,
            ],
            [
                'name' => 'Editorial Sudamericana',
                'description' => 'Argentine publisher of fiction and literature.',
                'website' => 'https://www.sudamericana.com.ar',
                'email' => 'info@sudamericana.com.ar',
                'phone' => '+54-11-43527000',
                'country' => 'Argentina',
                'city' => 'Buenos Aires',
                'is_active' => true,
            ],
            [
                'name' => '重庆出版社',
                'description' => 'Chinese publisher based in Chongqing.',
                'website' => 'https://www.cqpress.com.cn',
                'email' => 'info@cqpress.com.cn',
                'phone' => '+86-23-63898000',
                'country' => 'China',
                'city' => 'Chongqing',
                'is_active' => true,
            ],
            [
                'name' => '新潮社',
                'description' => 'Japanese publisher known for literature and quality books.',
                'website' => 'https://www.shinchosha.co.jp',
                'email' => 'info@shinchosha.co.jp',
                'phone' => '+81-3-36663730',
                'country' => 'Japan',
                'city' => 'Tokyo',
                'is_active' => true,
            ],
            [
                'name' => '민음사',
                'description' => 'Korean publisher of literature and novels.',
                'website' => 'https://www.minumsa.com',
                'email' => 'info@minumsa.com',
                'phone' => '+82-2-31050000',
                'country' => 'South Korea',
                'city' => 'Seoul',
                'is_active' => true,
            ],
        ];

        foreach ($publishers as $publisher) {
            Publisher::updateOrCreate(
                ['name' => $publisher['name']],
                $publisher
            );
        }
    }
}
