<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Book;
use App\Models\Publisher;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        // Get all publishers indexed by name for quick lookup
        $publishers = Publisher::all()->keyBy('name');

        $books = [
            [
                'title' => 'Harry Potter and the Philosopher\'s Stone',
                'description' => 'The first book in the Harry Potter series. Follow young Harry as he discovers his magical heritage and attends Hogwarts School of Witchcraft and Wizardry.',
                'price' => 374850,
                'isbn' => '978-0747532699',
                'pages' => 223,
                'language' => 'English',
                'publication_year' => 1997,
                'publisher_id' => $publishers['Bloomsbury Publishing']->id ?? null,
                'status' => 'available',
                'author_id' => 1,
                'category_id' => 3,
                'cover_image_url' => 'product_image/front/harry-potter-and-the-philosopher-s-stone-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fantasy', 'Magic', 'Adventure']),
                'weight_grams' => 350,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'The Shining',
                'description' => 'A family heads to an isolated hotel for the winter where a sinister presence influences the father into violence, while his psychic son sees horrific forebodings from both past and future.',
                'price' => 299850,
                'isbn' => '978-0307743657',
                'pages' => 447,
                'language' => 'English',
                'publication_year' => 1977,
                'publisher_id' => $publishers['Doubleday']->id ?? null,
                'status' => 'available',
                'author_id' => 2,
                'category_id' => 4,
                'cover_image_url' => 'product_image/the-shining-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Horror', 'Psychological', 'Supernatural']),
                'weight_grams' => 420,
                'is_featured' => 1,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'The Great Gatsby',
                'description' => 'A classic American novel set in the Jazz Age, exploring themes of decadence, idealism, and the American Dream through the eyes of narrator Nick Carraway.',
                'price' => 224775,
                'isbn' => '978-0743273565',
                'pages' => 180,
                'language' => 'English',
                'publication_year' => 1925,
                'publisher_id' => $publishers['Charles Scribner\'s Sons']->id ?? null,
                'status' => 'available',
                'author_id' => 4,
                'category_id' => 1,
                'cover_image_url' => 'product_image/the-great-gatsby-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Classic', 'Literary Fiction', 'Drama']),
                'weight_grams' => 220,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'Pride and Prejudice',
                'description' => 'Elizabeth Bennet navigates matters of morality, education, and marriage in the society of the landed gentry of early 19th-century England.',
                'price' => 269730,
                'isbn' => '978-0141439518',
                'pages' => 432,
                'language' => 'English',
                'publication_year' => 1813,
                'publisher_id' => $publishers['Penguin Classics']->id ?? null,
                'status' => 'available',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image_url' => 'product_image/pride-and-prejudice-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Romance', 'Literary Fiction', 'Classic']),
                'weight_grams' => 390,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'Murder on the Orient Express',
                'description' => 'Hercule Poirot investigates a murder aboard the luxurious Orient Express train when a wealthy American passenger is found dead in his compartment.',
                'price' => 254485,
                'isbn' => '978-0062693662',
                'pages' => 256,
                'language' => 'English',
                'publication_year' => 1934,
                'publisher_id' => $publishers['Collins Crime Club']->id ?? null,
                'status' => 'available',
                'author_id' => 3,
                'category_id' => 4,
                'cover_image_url' => '/book_covers/1779285096_6a0dbc6832643.jpeg',
                'images' => json_encode([]),
                'genres' => json_encode(['Mystery', 'Crime', 'Detective']),
                'weight_grams' => 280,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'Kafka on the Shore',
                'description' => 'A teenage boy runs away from home to escape an Oedipal prophecy. In another narrative, a man who wakes up to find that his name, and the memory of his body, have been wiped from the world.',
                'price' => 329790,
                'isbn' => '978-1400079278',
                'pages' => 505,
                'language' => 'English',
                'publication_year' => 2002,
                'publisher_id' => $publishers['Knopf']->id ?? null,
                'status' => 'available',
                'author_id' => 6,
                'category_id' => 1,
                'cover_image_url' => 'product_image/kafka-on-the-shore-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Magical Realism', 'Surrealism', 'Literary Fiction']),
                'weight_grams' => 420,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'Dune',
                'description' => 'An epic science fiction novel about Paul Atreides, a young man destined to lead humanity to a brighter future on the desert planet Arrakis.',
                'price' => 389820,
                'isbn' => '978-0441172719',
                'pages' => 688,
                'language' => 'English',
                'publication_year' => 1965,
                'publisher_id' => $publishers['Ace Books']->id ?? null,
                'status' => 'available',
                'author_id' => 7,
                'category_id' => 5,
                'cover_image_url' => 'product_image/dune-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Science Fiction', 'Epic', 'Adventure']),
                'weight_grams' => 640,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'Foundation',
                'description' => 'The story of humanity\'s last attempt to preserve civilization, as a great empire crumbles. Hari Seldon foresees the fall and creates a refuge of knowledge.',
                'price' => 314685,
                'isbn' => '978-0553293357',
                'pages' => 247,
                'language' => 'English',
                'publication_year' => 1951,
                'publisher_id' => $publishers['Bantam Spectra']->id ?? null,
                'status' => 'available',
                'author_id' => 8,
                'category_id' => 5,
                'cover_image_url' => 'product_image/foundation-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Science Fiction', 'Epic', 'Classic']),
                'weight_grams' => 350,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'Educated',
                'description' => 'A memoir about a young woman who leaves her survivalist family and becomes educated, going from the mountains of Idaho to Cambridge University.',
                'price' => 359235,
                'isbn' => '978-0399590504',
                'pages' => 352,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Random House']->id ?? null,
                'status' => 'available',
                'author_id' => 9,
                'category_id' => 6,
                'cover_image_url' => 'product_image/educated-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Memoir', 'Biography', 'Education']),
                'weight_grams' => 420,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'Becoming',
                'description' => 'Michelle Obama invites readers into her world, chronicling her life from childhood through her years as First Lady of the United States.',
                'price' => 374850,
                'isbn' => '978-1524763138',
                'pages' => 426,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Crown Publishing Group']->id ?? null,
                'status' => 'available',
                'author_id' => 10,
                'category_id' => 6,
                'cover_image_url' => 'product_image/becoming-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Memoir', 'Biography', 'Politics']),
                'weight_grams' => 480,
                'is_featured' => 1,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'The Handmaid\'s Tale',
                'description' => 'In a dystopian future, a woman is forced to bear children for the state in this chilling exploration of power, freedom, and survival.',
                'price' => 329790,
                'isbn' => '978-0385490238',
                'pages' => 395,
                'language' => 'English',
                'publication_year' => 1985,
                'publisher_id' => $publishers['Houghton Mifflin']->id ?? null,
                'status' => 'available',
                'author_id' => 11,
                'category_id' => 3,
                'cover_image_url' => '/book_covers/1779284345_6a0db97991d35.jpeg',
                'images' => json_encode([]),
                'genres' => json_encode(['Dystopian', 'Science Fiction', 'Political']),
                'weight_grams' => 390,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'A Game of Thrones',
                'description' => 'The first book in the epic A Song of Ice and Fire series. Political intrigue, war, and dragons in the Seven Kingdoms of Westeros.',
                'price' => 449780,
                'isbn' => '978-0553103540',
                'pages' => 694,
                'language' => 'English',
                'publication_year' => 1996,
                'publisher_id' => $publishers['Bantam Books']->id ?? null,
                'status' => 'available',
                'author_id' => 4,
                'category_id' => 3,
                'cover_image_url' => 'product_image/a-game-of-thrones-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fantasy', 'Epic', 'Political Intrigue']),
                'weight_grams' => 650,
                'is_featured' => 1,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
            [
                'title' => 'Sapiens: A Brief History of Humankind',
                'description' => 'An exploration of the history of humankind, from the Stone Age to the modern age, examining how Homo sapiens came to dominate Earth.',
                'price' => 344775,
                'isbn' => '978-0062316097',
                'pages' => 443,
                'language' => 'English',
                'publication_year' => 2011,
                'publisher_id' => $publishers['Harper']->id ?? null,
                'status' => 'available',
                'author_id' => 12,
                'category_id' => 2,
                'cover_image_url' => 'product_image/sapiens-a-brief-history-of-humankind-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['History', 'Anthropology', 'Science']),
                'weight_grams' => 480,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'Atomic Habits',
                'description' => 'A comprehensive guide to breaking bad habits and adopting good ones through small, incremental changes that lead to remarkable results.',
                'price' => 284535,
                'isbn' => '978-0735211292',
                'pages' => 320,
                'language' => 'English',
                'publication_year' => 2018,
                'publisher_id' => $publishers['Avery']->id ?? null,
                'status' => 'available',
                'author_id' => 13,
                'category_id' => 8,
                'cover_image_url' => 'product_image/atomic-habits-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Self-Help', 'Psychology', 'Productivity']),
                'weight_grams' => 380,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'The Psychology of Money',
                'description' => 'Timeless lessons on wealth, greed, and happiness through a collection of essays on how people think about money and make financial decisions.',
                'price' => 269730,
                'isbn' => '978-0857197689',
                'pages' => 256,
                'language' => 'English',
                'publication_year' => 2020,
                'publisher_id' => $publishers['Harriman House']->id ?? null,
                'status' => 'available',
                'author_id' => 14,
                'category_id' => 2,
                'cover_image_url' => 'product_image/the-psychology-of-money-front.jpg',
                'images' => json_encode([]),
                'genres' => json_encode(['Finance', 'Psychology', 'Business']),
                'weight_grams' => 290,
                'is_featured' => 0,
                'cover_type' => 'softcover',
                'stock' => 12,
            ],
            [
                'title' => 'The Midnight Library',
                'description' => 'Nora Seed finds herself in a library between life and death where she can explore the different lives she could have lived and make different choices.',
                'price' => 299850,
                'isbn' => '978-0020468623',
                'pages' => 304,
                'language' => 'English',
                'publication_year' => 2020,
                'publisher_id' => $publishers['Viking']->id ?? null,
                'status' => 'available',
                'author_id' => 5,
                'category_id' => 1,
                'cover_image_url' => '/book_covers/1779284285_6a0db93d492b7.jpeg',
                'images' => json_encode([]),
                'genres' => json_encode(['Fiction', 'Fantasy', 'Contemporary']),
                'weight_grams' => 350,
                'is_featured' => 0,
                'cover_type' => 'hardcover',
                'stock' => 12,
            ],
        ];

        foreach ($books as $book) {
            Book::firstOrCreate(
                ['isbn' => $book['isbn']],
                $book
            );
        }
    }
}

